# Generated by Django 4.2 on 2024-12-24 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='HashTag',
            new_name='hashtags',
        ),
    ]
